'use strict';

// tests for download
// Generated by serverless-mocha-plugin

const mod = require('../download/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const download = require('./payload.json');

describe('download', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () =>
    wrapped.run(download).then((response) => {
      expect(response).to.not.be(undefined);
    }));
});
