'use strict';

// tests for facebook
// Generated by serverless-mocha-plugin

const mod = require('../facebook/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const payload = require('./payload-metadata.json');

describe('facebook', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () =>
    wrapped.run(payload).then((response) => {
      console.log(response);
      expect(response).to.not.be(undefined);
    }));
});
